require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - node_modules/**/*
    - db/**
    - db/migrate/**
    - bin/**
    - vendor/**/*
    - vendor/**/*
    - lib/tasks/cucumber.rake
    - data/*

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive
